# Generated by Django 4.1.7 on 2023-03-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_symposiuminfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symposiuminfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='symposiuminfo',
            name='dept',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('CSBS', 'Computer Science and Business Systems'), ('MBA', 'Master of Business Administration'), ('AIDS', 'Artificial Intelligence and Data Science'), ('CCE', 'Computer Science and Communication Engineering'), ('IT', 'Information Technology')], max_length=100, primary_key=True, serialize=False),
        ),
    ]
