# Generated by Django 4.1.7 on 2023-03-07 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_fileupload_certificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
