# Generated by Django 4.1.7 on 2023-03-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_remove_symposiuminfo_id_alter_symposiuminfo_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='Dept',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('CSBS', 'Computer Science and Business Systems'), ('AIDS', 'Artificial Intelligence and Data Science'), ('CCE', 'Computer and Communication Engineering'), ('IT', 'Information Technology')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('CSBS', 'Computer Science and Business Systems'), ('AIDS', 'Artificial Intelligence and Data Science'), ('CCE', 'Computer and Communication Engineering'), ('IT', 'Information Technology')], max_length=100),
        ),
        migrations.AlterField(
            model_name='symposiuminfo',
            name='dept',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('CSBS', 'Computer Science and Business Systems'), ('AIDS', 'Artificial Intelligence and Data Science'), ('CCE', 'Computer and Communication Engineering'), ('IT', 'Information Technology')], max_length=100, primary_key=True, serialize=False),
        ),
    ]
