# Generated by Django 4.1.7 on 2023-03-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_certificate_dept_alter_department_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='College',
            field=models.CharField(max_length=100),
        ),
    ]
